### ISSUE TITLE
DRCS外字を無視するオプションを追加してほしい

### ISSUE THREAD

**Issue by lamrongol** [nekopanda/Amatsukaze#12]
単なる要望で申し訳ないのですが、DRCS外字があった時エラー終了するのではなく無視してエンコードするオプションが欲しいです。

**Comment by nekopanda** [comment]
既にある「マッピングにないDRCS外字は無視する」ではなくて？

**Comment by lamrongol** [comment]
あ、こういうオプションがあったんですね。申し訳ありません。ありがとうございます。
