### ISSUE TITLE
ログファイルを出力しないオプションが欲しい

### ISSUE THREAD

**Issue by lamrongol** [nekopanda/Amatsukaze#13]
こちらも単なる要望で申し訳ないのですが、ログファイルを出力しないオプションが欲しいです。

**Comment by nekopanda** [comment]
既にある「ログファイルを出力先に生成しない」ではなくて？

**Comment by lamrongol** [comment]
こちらもありがとうございます。解決しました。あとCMカットのオプションにも気づきました。
