### ISSUE TITLE
25FPSになってしまう件

### ISSUE THREAD

**Issue by supertoppo7** [nekopanda/Amatsukaze#2]
大変便利に使わせていただいています。毎回、素晴らしいアップデートに感謝します。

さて、一部のTSファイルで25FPSになってしまうことがあります。問題が起きないものがほとんどです。問題が起きたTSファイルをHandBrakeでは問題なく処理できるようです。

お手数ですが、どうかよろしくお願いいたします。

Amatsukaze - Automated MPEG2-TS Transcoder
Built on Feb 18 2018 21:18:52
Copyright (c) 2017-2018 Nekopanda
AMT [info] [設定]
AMT [info] 入力: R:/Rec/ａｎｏｎｅ＃０６.ts
AMT [info] 出力: V:/ａｎｏｎｅ＃０６
AMT [info] 一時フォルダ: C:\Temp\amt9084444
AMT [info] 出力フォーマット: MP4
AMT [info] エンコーダ: C:\Tool_Program\Video\Amatsukaze\exe_files\x265_2.6+37_x64.exe (x265)
AMT [info] エンコーダオプション: --preset fast --profile main10 --crf 24
AMT [info] 自動ビットレート: 無効
AMT [info] エンコード/出力: 1パス/CMをカット
AMT [info] チャプター解析: 有効（ロゴ必須）
AMT [info] logo1: C:\Tool_Program\Video\Amatsukaze\logo\SID2088-1.lgd
AMT [info] ロゴ消し: する
AMT [info] 字幕: 有効
AMT [info] DRCSマッピング: C:\Tool_Program\Video\Amatsukaze\drcs\drcs_map.txt
AMT [info] サービスID: 2088
AMT [info] デコーダ: MPEG2:CUVID H264:CUVID
AMT [info] エンコーダでのインタレ解除: なし
AMT [info] [PAT更新]
AMT [info] サービス 2088 を選択
AMT [info] [PMT更新]
AMT [info] PID: 0x0100 TYPE: MPEG2-VIDEO
AMT [info] PID: 0x0110 TYPE: ADTS AAC
AMT [info] PID: 0x0130 TYPE: 字幕
AMT [info] PID: 0x0138 TYPE: 字幕
AMT [debug] 必要な情報は取得したのでTSを最初から読み直します
AMT [info] 開始Clock: 154334757724
AMT [info] 音声パーサ 0 を追加
AMT [info] [音声0フォーマット変更]
AMT [info] チャンネル: ステレオ サンプルレート: 48000
AMT [info] [映像フォーマット変更]
AMT [info] サイズ: 1440x1080 FPS: 30000/1001
AMT [info] [PMT更新] ストリーム時刻: 0分5.37秒
AMT [info] PID: 0x0100 TYPE: MPEG2-VIDEO
AMT [info] PID: 0x0110 TYPE: ADTS AAC
AMT [info] PID: 0x0111 TYPE: ADTS AAC
AMT [info] PID: 0x0130 TYPE: 字幕
AMT [info] PID: 0x0138 TYPE: 字幕
AMT [info] 音声パーサ 1 を追加
AMT [info] [音声1フォーマット変更]
AMT [info] チャンネル: ステレオ サンプルレート: 48000
AMT [info] [PMT更新] ストリーム時刻: 60分5.39秒
AMT [info] PID: 0x0100 TYPE: MPEG2-VIDEO
AMT [info] PID: 0x0110 TYPE: ADTS AAC
AMT [info] PID: 0x0130 TYPE: 字幕
AMT [info] PID: 0x0138 TYPE: 字幕
AMT [info] [映像フレーム統計情報]
AMT [info] 時間: 60分6.903秒
AMT [info] FRAME=0 DBL=0 TLP=0 TFF=108102 BFF=0 TFF_RFF=0 BFF_RFF=0
AMT [info] (PTS_Diff,Cnt)=(3003,108101)
AMT [info] TS解析完了: 54.60秒
AMT [info] [フォーマット切り替え解析]
AMT [info] 0.00 -> 0
AMT [info] 5.00 -> 1
AMT [info] 3605.10 -> 0
AMT [info] [CM判定用音声構築]
AMT [debug] 音声-1-0は26フレーム目から開始
AMT [info] [ロゴ解析]
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
AMT [info]      0/108100
AMT [info]   5000/108100
AMT [info]  10000/108100
AMT [info]  15000/108100
AMT [info]  20000/108100
AMT [info]  25000/108100
AMT [info]  30000/108100
AMT [info]  35000/108100
AMT [info]  40000/108100
AMT [info]  45000/108100
AMT [info]  50000/108100
AMT [info]  55000/108100
AMT [info]  60000/108100
AMT [info]  65000/108100
AMT [info]  70000/108100
AMT [info]  75000/108100
AMT [info]  80000/108100
AMT [info]  85000/108100
AMT [info]  90000/108100
AMT [info]  95000/108100
AMT [info] 100000/108100
AMT [info] 105000/108100
AMT [info] Finished
AMT [info] 完了: 157.63秒
AMT [info] [ロゴ解析結果]
AMT [info] マッチしたロゴ: C:\Tool_Program\Video\Amatsukaze\logo\SID2088-1.lgd
   174 S 0 ALL    174    174
 17988 E 0 ALL  17988  17988
 21602 S 0 ALL  21602  21602
 37080 E 0 ALL  37080  37080
 37727 S 0 ALL  37727  37727
 44422 E 0 ALL  44422  44422
 48037 S 0 ALL  48037  48037
 66719 E 0 ALL  66719  66719
 70334 S 0 ALL  70334  70334
 83472 E 0 ALL  83472  83472
 87537 S 0 ALL  87537  87537
108049 E 0 ALL 108049 108049
AMT [info] [無音・シーンチェンジ解析]
AMT [info] "C:\Tool_Program\Video\Amatsukaze\exe_files\chapter_exe.exe" -v "C:\Temp\amt9084444/amts0.avs" -o "C:\Temp\amt9084444/chapter_exe0.txt"
[mpeg2_cuvid @ 00000250713fb580] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
[mpeg2_cuvid @ 00000250713feb00] Invalid pkt_timebase, passing timestamps as-is.
AMT [info] 完了: 18.69秒
AMT [info] [無音・シーンチェンジ解析結果]
Setting
	video: C:\Temp\amt9084444/amts0.avs
	audio: (within video source)
	out: C:\Temp\amt9084444/chapter_exe0.txt
	mute: 50 seri: 10 bmute: 60 emute: 1
Movie data
	Video Frames: 108100 [29.97fps]
	Audio Samples: 173121536 [48000Hz]
--------
mute 1: 149 - 33フレーム
	 SCPos: 164 
mute 2: 7788 - 10フレーム
	 SCPos: 7790 ＿
mute 3: 7935 - 33フレーム
	 SCPos: 7957 
mute 4: 7969 - 10フレーム
	 SCPos: 7978 ＿
mute 5: 8031 - 18フレーム
	 SCPos: 8037 ＿
mute 6: 8066 - 34フレーム
	 SCPos: 8095 
mute 7: 8142 - 34フレーム
	 SCPos: 8175 ＿
mute 8: 10608 - 12フレーム
	 SCPos: 10619 
mute 9: 11054 - 11フレーム
	 SCPos: 11053 ★
mute10: 11066 - 17フレーム
	 SCPos: 11066 ＿
mute11: 17984 - 29フレーム
	 SCPos: 17997 
mute12: 18433 - 31フレーム
	 SCPos: 18447 ★
mute13: 18884 - 30フレーム
	 SCPos: 18896 ★
mute14: 19332 - 30フレーム
	 SCPos: 19346 ★
mute15: 19777 - 33フレーム
	 SCPos: 19795 ★
mute16: 20679 - 32フレーム
	 SCPos: 20695 ★★
muauto detect CutMrgIn=8 CutMrgOut=8
current set CutMrgIn=8 CutMrgOut=8
te17: 21536 - 74フレーム
	 SCPos: 21535 ＠
	 SCPos: 21594 ★★
mute18: 35654 - 12フレーム
	 SCPos: 35653 ＿
mute19: 41871 - 38フレーム
	 SCPos: 41894 ＿
mute20: 44332 - 50フレーム
	 SCPos: 44355 ＿
mute21: 44407 - 40フレーム
	 SCPos: 44431 
mute22: 45316 - 29フレーム
	 SCPos: 45330 ★★
mute23: 45765 - 29フレーム
	 SCPos: 45779 ★
mute24: 46214 - 31フレーム
	 SCPos: 46229 ★
mute25: 47100 - 45フレーム
	 SCPos: 47128 ★★
mute26: 48004 - 40フレーム
	 SCPos: 48013 ＠
	 SCPos: 48027 ★★
mute27: 50235 - 11フレーム
	 SCPos: 50244 ＿
mute28: 50767 - 13フレーム
	 SCPos: 50766 ＿
mute29: 51043 - 14フレーム
	 SCPos: 51042 ＿
mute30: 51063 - 27フレーム
	 SCPos: 51062 ＿
mute31: 51514 - 11フレーム
	 SCPos: 51513 ＿
mute32: 51549 - 10フレーム
	 SCPos: 51548 ＿
mute33: 51611 - 34フレーム
	 SCPos: 51610 ＿
mute34: 51646 - 77フレーム
	 SCPos: 51718 ＿
mute35: 51850 - 13フレーム
	 SCPos: 51856 ＿
mute36: 52083 - 29フレーム
	 SCPos: 52082 ＿
mute37: 52304 - 28フレーム
	 SCPos: 52303 ＿
mute38: 52383 - 24フレーム
	 SCPos: 52382 ＿
mute39: 52460 - 12フレーム
	 SCPos: 52459 ＿
mute40: 52592 - 20フレーム
	 SCPos: 52598 ＿
mute41: 52678 - 91フレーム
	 SCPos: 52677 ＿
mute42: 56154 - 25フレーム
	 SCPos: 56162 ＿
mute43: 56180 - 13フレーム
	 SCPos: 56192 ＿
mute44: 56199 - 13フレーム
	 SCPos: 56207 ＿
mute45: 56245 - 20フレーム
	 SCPos: 56257 ＿
mute46: 58669 - 20フレーム
	 SCPos: 58687 ＿
mute47: 59573 - 12フレーム
	 SCPos: 59583 ＿
mute48: 59617 - 20フレーム
	 SCPos: 59638 ＿
mute49: 59657 - 12フレーム
	 SCPos: 59670 ＿
mute50: 59826 - 18フレーム
	 SCPos: 59845 ＿
mute51: 59845 - 14フレーム
	 SCPos: 59854 ＿
mute52: 59927 - 10フレーム
	 SCPos: 59927 ＿
mute53: 60047 - 13フレーム
	 SCPos: 60057 ＿
mute54: 60124 - 11フレーム
	 SCPos: 60123 ＿
mute55: 66702 - 43フレーム
	 SCPos: 66728 
mute56: 67164 - 30フレーム
	 SCPos: 67178 ★
mute57: 67377 - 10フレーム
	 SCPos: 67381 
mute58: 67549 - 13フレーム
	 SCPos: 67558 
mute59: 67614 - 30フレーム
	 SCPos: 67627 
mute60: 68512 - 30フレーム
	 SCPos: 68527 ★★
mute61: 69409 - 33フレーム
	 SCPos: 69426 ★★
mute62: 70312 - 29フレーム
	 SCPos: 70325 ★★
mute63: 83464 - 32フレーム
	 SCPos: 83482 
mute64: 83917 - 28フレーム
	 SCPos: 83931 ★
mute65: 84365 - 30フレーム
	 SCPos: 84381 ★
mute66: 84815 - 30フレーム
	 SCPos: 84830 ★
mute67: 85264 - 30フレーム
	 SCPos: 85280 ★
mute68: 86164 - 30フレーム
	 SCPos: 86179 ★★
mute69: 86613 - 32フレーム
	 SCPos: 86628 ★
mute70: 87064 - 28フレーム
	 SCPos: 87078 ★
mute71: 87512 - 32フレーム
	 SCPos: 87528 ★
mute72: 98093 - 12フレーム
	 SCPos: 98093 ＿
mute73: 98639 - 16フレーム
	 SCPos: 98645 ＿
mute74: 105873 - 14フレーム
	 SCPos: 105872 ＿
mute75: 107292 - 32フレーム
	 SCPos: 107308 
mute76: 107669 - 16フレーム
	 SCPos: 107668 
mute77: 107744 - 15フレーム
	 SCPos: 107757 
mute78: 107886 - 38フレーム
	 SCPos: 107907 
mute79: 108044 - 29フレーム
	 SCPos: 108057 
AMT [info] [CM解析]
AMT [info] "C:\Tool_Program\Video\Amatsukaze\exe_files\join_logo_scp.exe" -inlogo "C:\Temp\amt9084444/logof0.txt" -inscp "C:\Temp\amt9084444/chapter_exe0.txt" -incmd "C:\Tool_Program\Video\Amatsukaze\JL\JL_標準.txt" -o "C:\Temp\amt9084444/trim0.avs" -oscp "C:\Temp\amt9084444/jls0.txt" 
AMT [info] 完了: 0.04秒
AMT [info] [CM解析結果 - TrimAVS]
Trim(165,17996) ++ Trim(21594,44430) ++ Trim(48028,66727) ++ Trim(70325,83481) ++ Trim(87528,108056)
AMT [info] [CM解析結果 - 詳細]
     0    163    6 -15    0 :Nologo
   165  17996  595   1  595 :L
 17998  18446   15  -1    0 :CM
 18447  18895   15  -1    0 :CM
 18896  19345   15   0    0 :CM
 19346  19794   15  -1    0 :CM
 19795  20694   30   1    0 :CM
 20695  21593   30   0    0 :CM
 21594  44430  762   0  741 :Mix
 44431  45329   30   0    0 :CM
 45330  45778   15  -1    0 :CM
 45779  46228   15   0    0 :CM
 46229  47127   30   0    0 :CM
 47128  48026   30   1    0 :CM
 48028  66727  624   0  624 :L
 66729  67177   15  -1    0 :CM
 67178  67626   15   0    0 :CM
 67628  68526   30   0    0 :CM
 68527  69425   30   0    0 :CM
 69426  70324   30   0    0 :CM
 70325  83481  439   0  439 :L
 83482  83930   15  -1    0 :CM
 83931  84380   15   0    0 :CM
 84381  84829   15  -1    0 :CM
 84830  85279   15   0    0 :CM
 85280  86178   30   0    0 :CM
 86179  86627   15  -1    0 :CM
 86628  87077   15   0    0 :CM
 87078  87527   15   0    0 :CM
 87528 107307  660   0  660 :L
107308 107756   15   0   15 :Trailer(add)
107758 107906    5   0    5 :Sponsor(add)
107908 108056    5   0    5 :Endcard(add)
108058 108099    1  11    0 :Nologo
AMT [info] [チャプター生成]
AMT [info] ファイル: 0-1 本編
AMT [info]     0: A
AMT [info] 17832: B
AMT [info] 40669: C
AMT [info] 59369: D
AMT [info] 72526: E
AMT [info] 92306: E15Sec
AMT [info] 92756: E5Sec
AMT [info] 92906: E5Sec
AMT [info] ロゴ・CM解析完了: 176.39秒
AMT [info] [字幕構築]
AMT [info] [音声構築]
AMT [debug] 音声0-0は26フレーム目から開始
AMT [debug] 音声1-0は257フレーム目から開始
AMT [debug] 0分5.005秒で音声1-1の同期ポイントを見失ったので再検索
AMT [debug] 0分5.528秒で音声1-1にずれがあるので23フレーム水増し
AMT [debug] 0分5.517秒で音声1-1の同期ポイントを見失ったので再検索
AMT [debug] 60分4.770秒で音声1-1の同期ポイントを見失ったので再検索
AMT [debug] 60分5.123秒で音声0-0にずれがあるので168755フレームスキップ
AMT [info] 出力音声フレーム: 337804（うち水増しフレーム23）
AMT [info] 未出力フレーム: 24（0.007%）
AMT [info] 音ズレ: 平均 10.68ms 最大 522.91ms
AMT [info] 最大音ズレ位置: 入力最初の映像フレームから0分5.005秒後
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
AMT [info] フィルタ入力: 93041フレーム 30000/1001fps (インターレース)
AMT [info] フィルタ出力: 186082フレーム 60000/1001fps (プログレッシブ)
AMT [info] [エンコード開始] 2/2 本編
AMT [info] 入力映像ビットレート: 13583 kbps
AMT [info] 1/1パス エンコード開始 予定フレーム数: 186082
AMT [info] [エンコーダ起動]
AMT [info] "C:\Tool_Program\Video\Amatsukaze\exe_files\x265_2.6+37_x64.exe" --colorprim bt709 --transfer bt709 --colormatrix bt709 --no-interlace --preset fast --profile main10 --crf 24 -o "C:\Temp\amt9084444/v0-1-main.raw" --no-opt-qp-pps --no-opt-ref-list-length-pps --y4m --input -
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [info] Output #0, yuv4mpegpipe, to '-':
FFMPEG [info]     Stream #0:0: Video: wrapped_avframe, yuv420p10le(bt709, progressive), 1440x1080 [SAR 4:3 DAR 16:9], q=2-31, 200 kb/s, 59.94 fps, 59.94 tbn
FFMPEG [warn] Warning: generating non standard YUV stream. Mjpegtools will not work.
y4m  [info]: 1440x1080 fps 60000/1001 i420p10 sar 4:3 unknown frame count
raw  [info]: output file: C:\Temp\amt9084444/v0-1-main.raw
x265 [info]: HEVC encoder version 2.6+37-1949157705ce
x265 [info]: build info [Windows][MSVC 1912][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-4.1 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(17 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 2
x265 [info]: Keyframe min / max / scenecut / bias: 25 / 250 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 15 / 4 / 0
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / on / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 1 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-24.0 / 0.60
x265 [info]: tools: rd=2 psy-rd=2.00 rskip signhide tmvp fast-intra
x265 [info]: tools: strong-intra-smoothing lslices=6 deblock sao
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
FFMPEG [warn] Invalid pkt_timebase, passing timestamps as-is.
x265 [info]: frame I:    954, Avg QP:23.94  kb/s: 12564.78
x265 [info]: frame P:  36798, Avg QP:26.44  kb/s: 1711.90 
x265 [info]: frame B: 148330, Avg QP:34.16  kb/s: 204.80  
x265 [info]: Weighted P-Frames: Y:0.6% UV:0.5%
x265 [info]: consecutive B-frames: 1.4% 0.2% 0.2% 0.3% 97.8% 
encoded 186082 frames in 3671.42s (50.68 fps), 566.20 kb/s, Avg QP:32.58
AMT [info] Total: 3672.66s, FilterWait: 2222.40s, EncoderWait: 4.48s
AMT [info] エンコード完了: 3673.13秒
AMT [info] [Mux開始] 2/2 本編
AMT [info] "C:\Tool_Program\Video\Amatsukaze\exe_files\muxer.exe" -i "C:\Temp\amt9084444/v0-1-main.raw" -i "C:\Temp\amt9084444/a0-1-0-main.aac" -i "C:\Temp\amt9084444/a0-1-1-main.aac" --chapter "C:\Temp\amt9084444/chapter0-1-main.txt" --optimize-pd -o "V:/ａｎｏｎｅ＃０６.mp4"
MP4 muxing mode
[HEVC: Info]: IDR: 1, CRA: 930, BLA: 0, I: 23, P: 36798, B: 148330, Unknown: 0
Track 1: H.265 High Efficiency Video Coding
Track 2: MPEG-4 Audio
Track 3: MPEG-4 Audio
Muxing completed!
AMT [info] "C:\Tool_Program\Video\Amatsukaze\exe_files\mp4box.exe" -add "C:\Temp\amt9084444/c0-1-0-main.srt#:name=SRT" "V:/ａｎｏｎｅ＃０６.mp4"
Timed Text (SRT) import - text track 1920 x 1080, font Serif (size 18)
Saving V:/ａｎｏｎｅ＃０６.mp4: 0.500 secs Interleaving
                                                        
AMT [info] Mux完了: 91.09秒
AMT [info] [出力ファイル]
AMT [info] 0: V:/ａｎｏｎｅ＃０６.mp4
AMT [info] 1: V:/ａｎｏｎｅ＃０６-1.mp4
AMT [info] [入力->出力マッピング]
AMT [info]   0分0.000秒 -   0分5.005秒 -> 1
AMT [info]   0分5.005秒 -  60分5.102秒 -> 0
AMT [info]  60分5.102秒 -  60分6.937秒 -> 1

**Comment by nekopanda** [comment]
報告ありがとうございます！頂いた情報でバグを見つけて修正しました。
 bf702547d56f6adeb6c837744d4e19cff4f905ac
修正版をリリースしたので、よろしくです。

**Comment by supertoppo7** [comment]
早速の対応、本当にありがとうございます。当方でも全く問題なく動作しました。心から感謝します。
