### ISSUE TITLE
VFRとCFRの出力ファイルサイズの大幅な違い

### ISSUE THREAD

**Issue by supertoppo7** [nekopanda/Amatsukaze#4]
便利に使わせていただいております。今回のバージョンアップで、更に使いやすくなっており、本当に感謝しています。要望をいろいろと取り入れてくださってありがとう御座います。

VFRを試しているのですが、同じソースで同じ品質で変換しても、CFRに比べてVFRのファイルサイズが1.8倍ほど大きくなっていまいます。以前、HandbrakeにてVFRを使用していた際は、このような違いはなく、むしろ、VFRの方がフレームが減る分、ファイルサイズが小さくなっていました。

ログを見ていたところ、x265のオプションがVFRとCFRで異なっていることに気が付きました。

CFR
AMT [info] "C:\Amatsukaze\exe_files\x265_2.7+338_x64.exe" --colorprim bt709 --transfer bt709 --colormatrix bt709 -P main10 --preset fast --crf 24  --asm avx2 -o "C:\Temp\amt2134932/v0-0-main.raw" --no-opt-qp-pps --no-opt-ref-list-length-pps --y4m --input -

VFR
AMT [info] "C:\Amatsukaze\exe_files\x265_2.7+338_x64.exe" --colorprim bt709 --transfer bt709 --colormatrix bt709 -P main10 --preset fast --crf 24  --asm avx2 --zones 0,11808,b=2.49/11808,11824,b=1/11824,12448,b=2.25/12448,23656,b=2.5/23656,23704,b=1.67/23704,30176,b=2.5/30176,30192,b=1.56/30192,34632,b=2.5/34632,35608,b=2.48/35608,35624,b=1.44/35624,39360,b=2.5/39360,39408,b=1.65/39408,46400,b=2.5/46400,46424,b=1.25/46424,46656,b=2.45/46656,46680,b=1.13/46680,46816,b=2.17/46816,57864,b=2.5/57864,57888,b=1.54/57888,74136,b=2.5/74136,74240,b=1.81/74240,75192,b=2.38/75192,75224,b=1.13/75224,79200,b=2.5/79200,82144,b=2.48/82144,82160,b=1.44/82160,82440,b=1.6/82440,82880,b=1/82880,82990,b=2.09 -o "C:\Temp\amt2129422/v0-0-main.raw" --no-opt-qp-pps --no-opt-ref-list-length-pps --y4m --input -

おそらく、VFRなときには、フレームの範囲ごとに画質を変えてくださっているのだと思います。深い意味があるものと思いますが、対処方法をお教えいただければ幸いです。

**Comment by nekopanda** [comment]
報告ありがとうございます。

VFRで24fpsで出力されたときと、CFR60fpsで出力したときとで、ビットレートを同じにしようとしたのですが、全然違いますね！！

調整します。

**Comment by supertoppo7** [comment]
対応、心から感謝します。
デフォルトで、CFR60FPSと同じ程度のビットレートにできました。
いつもながら、素早い対応、ありがとうございます。
