### ISSUE TITLE
AmatsukazeAddTaskの動作について

### ISSUE THREAD

**Issue by supertoppo7** [nekopanda/Amatsukaze#5]
いつも便利に使わせていただいています。以前から、AmatsukazeAddTaskを試そうとしているのですが、うまく動きません。申し訳ありませんが、教えていただけませんか。

AmatsukazeAddTask.exe -f "E:\Videos\TEST.ts" -s "x265_VFR" -o "V:\TEST" -ip "localhost" -p 32768

これを実行すると、サーバーのコンソールに「ストリームの末尾を超えて読み取ろうとしました」と出て実行できません。
試しに、AmatsukazeClientを起動して、そちらからタスクを登録すると、問題なくサーバー側で処理が進みます。

いつも細かい点で申し訳ありませんが、どうかよろしくお願いします。

**Comment by nekopanda** [comment]
情報が足りなくて分かりません。「ストリームの末尾を超えて読み取ろうとしました」は、クライアントが正常に終了しても常に出るのでエラーではありません。

AmatsukazeAddTaskの標準出力に何か吐いてたりしませんか？タスクがサーバに登録されなければエラーを表示するようになってて、正常に登録されれば「N件追加しました」と出るようになっているので、何かしら出てるんじゃないかと思います。

**Comment by supertoppo7** [comment]
説明が足りなくてすみません。

AmatsukazeAddTaskの標準出力には、
サーバのリクエスト受理を確認できませんでした。
再試行します・・・
サーバのリクエスト受理を確認できませんでした。
再試行します・・・
サーバのリクエスト受理を確認できませんでした。
と表示されていました。

何度かテストしたのですが、予めAmatsukazeサーバが起動しておけば、問題なくタスクが追加されることに気が付きました。

ただ、全く同じことをコマンドラインから入力しても、うまくいくときと再試行を繰り返してタスク登録されないこともあります。

今のところ、こちらで気がついたのは上記の点です。もう少し試してみて、気がついたことがあれば報告させていただきます。

**Comment by nekopanda** [comment]
多分、AmatsukazeAddTask.exeをAmatsukazeルートフォルダとは別の場所から起動しているのではないかと思います。

AmatsukazeAddTask.exeは単独で使うことを想定していなかった（生成したバッチファイルから使うこと前提だった）ので、Amatsukazeルートフォルダをカレントディレクトリにして起動する前提で作っていました。設定ファイルなど、もろもろのファイルはAmatsukzeルートフォルダが正しく設定されていないと、ファイルの場所が分からないので読めません。カレントディレクトリが別の場所だと、Amatsukazeサーバを起動したときにエラーになる可能性が高いです。

この仕様は分かりにくかったので、単独で使うことも想定して、exeの1つ上のフォルダをAmatsukazeルートフォルダとして、Amatsukazeサーバを起動するようにしました。https://github.com/nekopanda/Amatsukaze/commit/2b0cf3e6b9f1aa755770038c4e94b3f779ff4147

リリースパッケージのファイル構成ならこれでOKなので、カレントディレクトリに関係なくAmatsukazeサーバを起動できるようになると思います。リリースに含めたのでお試しください。

**Comment by supertoppo7** [comment]
いつも素早い対応、ありがとうございます。
作成されたバッチのテストをしていて、うまく動かなかったので、コマンドラインから試すときにAmatsukazeルートフォルダ以外で実行していました。
今回の対応で、全く問題なく動くようになりました。ありがとうございます。
どんどんと使いやすさや機能がアップしていて、本当に楽しみです。これからも、どうかよろしくお願いします。
