### ISSUE TITLE
プロファイルの管理に不具合がある

### ISSUE THREAD

**Issue by a1678991** [nekopanda/Amatsukaze#8]
Windowsではファイル名の大文字小文字は区別しないがプロファイル名では区別されている
その結果意図しないプロファイルの削除、更新が発生する可能性がある

**Comment by a1678991** [comment]
/\を含むプロファイルも適用できてしまいますがファイル名がすべて.profileになります

**Comment by nekopanda** [comment]
報告ありがとうございます。0.8.4.0 (コミット https://github.com/nekopanda/Amatsukaze/commit/c6e63a520747b8019b32ac863ca19bdd6341e9f8) で修正しました。
